---
title: "Carbon Counters Shiny App"
author: "Minnie Ringland, Alicia Fennell, Gavriella Keyles"
date: "2/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(sf) # for spatial data
library(tmap) # for interactive maps
library(janitor)
library(wesanderson)
```

```{r}
# Carbon Inventory
# dummy data for now - color coding by land type

ca_counties <- read_sf(here("data","ca_counties", "CA_Counties_TIGER2016.shp"))

ca_subset <- ca_counties %>% 
  select(NAME, ALAND) %>% 
  rename(county_name = NAME, land_area = ALAND)

# Set viewing mode to "interactive":
tmap_mode(mode = "view")

tm_shape(ca_subset) +
  tm_fill("land_area", palette = "Blues", title="Land area (sq meters)") +
  tm_borders(col = "white", lwd = 0.5) +
  tm_scale_bar()

```

```{r}
# Projection
# dummy dataset

matrix <- data.frame("year" = c(2016,2030),
                     "Acreage" = c(1, 1.3),
                     "Carbon" = c(2, 1.8),
                     "N2O" = c(3, 2.5)
                     )

matrix2 <- matrix %>% 
  select(year,Acreage) %>% 
  rename(new=Acreage)

ggplot(data = matrix) +
    geom_col(aes(x=year, y = N2O, fill = year))


```


```{r}
# Carbon-Smart Management Practices

projection <- read_csv(here("data","projections.csv"))

mgmt <- projection %>%
  pivot_wider(names_from = type, values_from = val) %>% 
  rename("Acreage"=2, "Carbon"=3, "N2O Emissions"=4) %>% 
  mutate("Composting" = matrix(0.5,11),
           "Cover" = matrix(1.5,11),
           "Restoration" = matrix(5,11)) %>% 
  mutate(newcol = Cover*Carbon*5/100)

ggplot(data = mgmt) +
    geom_col(aes(x=year, y = newcol))
 


```

```{r}
# Barriers to Implementation

barriers <- read_csv(here("data","barriers.csv"))

test <- barriers %>% 
  filter(barrier %in% "Cost/Funding")

```



```{r}

# Build inputs for projection

project_obs <- read_csv(here("data", "shiny_observed_30.csv"))

project_pred <- read_csv(here("data", "shiny_predict_30.csv"))

plot_project_react <- ggplot() +
 geom_line(data = subset(rev_plot_predict, variable == input$select_variable), aes(x = year, y = value, group = land_class, color = land_class), size = .8, linetype = "dashed") +
  geom_point(data = subset(tstock_plot_all, variable == input$select_variable), aes(x = year, y = value, group = land_class, color = land_class), size = 3.6) +
  theme_minimal() +
  scale_color_manual(values = c("lightsteelblue", "goldenrod", "lightslategrey", "darkred", "sandybrown", "darkolivegreen3", "green4", "cornflowerblue", "purple4")) +
  labs(color = "Land Class",
       y = input$variable,
       x = "") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30"))
```

```{r}

# Build inputs for management scenarios

mgmt_xl <- read_csv(here("data", "shiny_mgmt.csv")) %>% 
  clean_names() %>% 
  select(-2) %>% 
  rename_at(.vars = vars(starts_with("x")),
            .funs = funs(sub("x", "", .))) %>% 
  pivot_longer(cols = 2:16, 
               names_to = "year",
               values_to = "carbon_stock") %>% 
  separate(scenarios, sep = " - ", c("practice", "level"))

mgmt_practice <- mgmt_xl %>% 
  slice(-(1:15)) %>% 
  drop_na()

baseline <- mgmt_xl %>% 
  slice(1:15) %>% 
  select(!level)

wes_colors <- wes_palette("Darjeeling1", 7, type = "continuous")

ggplot() +
  geom_line(data = baseline, aes(x = year, y = carbon_stock, group = 1), color = "black") +
  geom_smooth(data = mgmt_practice, aes(x = year, y = carbon_stock, color = practice, linetype = level, group = interaction(practice, level))) + 
  theme_minimal() + 
  scale_color_manual(values = wes_colors) +
  labs(x = "Year",
       y = "Carbon Stock (million MT C)",
       color = "Management Practice",
       linetype = "Implementation Level")
  

```

